# Generated by Django 3.0.3 on 2020-02-24 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='created',
            new_name='date_create',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='updated',
            new_name='date_update',
        ),
    ]
