# Generated by Django 3.0.3 on 2020-02-28 05:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_orderlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderlist',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_course', to='courses.Course'),
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('name', models.CharField(blank=True, default='', max_length=100)),
                ('code', models.AutoField(primary_key=True, serialize=False)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_skills', to='courses.Course')),
            ],
        ),
    ]
