# Generated by Django 3.0.3 on 2020-02-28 06:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_remove_skill_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='skils',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='course_skils', to='courses.Skill'),
            preserve_default=False,
        ),
    ]
