# Generated by Django 3.0.3 on 2020-02-28 06:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_course_skils'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='skils',
        ),
        migrations.CreateModel(
            name='CourseSkils',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_id', to='courses.Course')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_id', to='courses.Skill')),
            ],
        ),
    ]
