# Generated by Django 3.0.3 on 2020-02-28 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_auto_20200228_1218'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CourseSkils',
            new_name='CourseSkills',
        ),
    ]
