# Generated by Django 3.0.3 on 2020-03-01 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_auto_20200228_1237'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='video_url',
            field=models.TextField(default=''),
        ),
    ]
