# Generated by Django 3.0.3 on 2020-03-03 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0002_lesson_module'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='questions',
        ),
        migrations.AddField(
            model_name='lesson',
            name='questions',
            field=models.ManyToManyField(related_name='questions', to='lessons.Question'),
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='videos',
        ),
        migrations.AddField(
            model_name='lesson',
            name='videos',
            field=models.ManyToManyField(related_name='videos', to='lessons.VideoLesson'),
        ),
    ]
