# Generated by Django 3.0.3 on 2020-03-03 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0003_auto_20200303_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='time',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
